[package]
name = "workspace-3d"
version = "0.2.0"
description = "3D Workspace — a personal studio for 3D models"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
