import { describe, expect, it } from 'vitest';
import { getPack, knownSkills } from '../src/content/registry';
import { eligibleItems, selectLevelItems } from '../src/content/selector';
import { createRng } from '../src/core/rng';
import { PROFILES } from '../src/learning/adaptive';
import { createLearner, recordResult } from '../src/learning/learner';
import { stripNiqqud } from '../src/content/hebrew/script';

const normal = PROFILES.normal;

describe('content packs', () => {
  for (const lang of ['en', 'he'] as const) {
    const pack = getPack(lang);
    it(`${lang}: every item is reachable through the curriculum`, () => {
      const all = knownSkills(pack, pack.units.length - 1);
      const unreachable = pack.items.filter((it) => !it.skills.every((s) => all.has(s)));
      expect(unreachable.map((x) => x.id)).toEqual([]);
    });
    it(`${lang}: every skill used by an item is defined`, () => {
      const missing = new Set(pack.items.flatMap((it) => it.skills).filter((s) => !pack.skills[s]));
      expect([...missing]).toEqual([]);
    });
    it(`${lang}: every unit has enough material for a level`, () => {
      pack.units.forEach((_, i) => expect(eligibleItems(pack, i).length).toBeGreaterThanOrEqual(4));
    });
    it(`${lang}: items carry the metadata the spec asks for`, () => {
      for (const it of pack.items) {
        expect(it.lang).toBe(lang);
        expect(it.display.length).toBeGreaterThan(0);
        expect(it.skills.length).toBeGreaterThan(0);
        expect(it.parts.length).toBeGreaterThan(0);
        expect(it.difficulty).toBeGreaterThan(0);
        expect(typeof it.isRealWord).toBe('boolean');
      }
    });
  }

  it('Hebrew and English have distinct progressions and directions', () => {
    const en = getPack('en'), he = getPack('he');
    expect(en.dir).toBe('ltr');
    expect(he.dir).toBe('rtl');
    expect(en.speechLang).toBe('en-US');
    expect(he.speechLang).toBe('he-IL');
    expect(he.units.map((u) => u.id)).not.toEqual(en.units.map((u) => u.id));
    expect(he.items.every((i) => /[א-ת]/.test(i.display))).toBe(true);
    expect(en.items.every((i) => /^[A-Za-z .,!?']+$/.test(i.display))).toBe(true);
  });

  it('early Hebrew words carry niqqud; stage-5 plain words do not', () => {
    const he = getPack('he');
    const w = he.items.find((i) => i.id === 'he:word:דָּג')!;
    expect(w.niqqud).toBe(true);
    expect(w.display).not.toBe(stripNiqqud(w.display));
    const plain = he.items.find((i) => i.id === 'he:plain:דָּג')!;
    expect(plain.display).toBe('דג');
    expect(plain.skills).toContain('he:P:plain');
  });

  it('CV syllables are generated by rule for every letter × vowel', () => {
    const he = getPack('he');
    const syl = he.items.filter((i) => i.kind === 'syllable');
    expect(syl.some((s) => s.display === 'בָּ'.normalize('NFC'))).toBe(true);
    expect(syl.some((s) => s.display === 'בִּ'.normalize('NFC'))).toBe(true);
    expect(syl.some((s) => s.display === 'בּוֹ'.normalize('NFC'))).toBe(true);
    expect(syl.every((s) => !s.isRealWord)).toBe(true);
  });
});

describe('item selection', () => {
  const en = getPack('en');
  const unit = (id: string) => en.units.findIndex((u) => u.id === id);

  it('only selects items whose skills have been taught', () => {
    const ui = unit('en-4');
    const known = knownSkills(en, ui);
    for (let seed = 1; seed < 20; seed++) {
      const sel = selectLevelItems(en, ui, createLearner(), { count: 8, rng: createRng(seed), profile: normal, boss: true });
      for (const it of [...sel.items, ...sel.boss]) expect(it.skills.every((s) => known.has(s))).toBe(true);
    }
  });

  it('first letter level uses only s a t p', () => {
    const sel = selectLevelItems(en, 0, createLearner(), { count: 6, rng: createRng(3), profile: normal });
    for (const it of sel.items) expect('satpSATP').toContain(it.display);
  });

  it('includes the unit\'s new skills', () => {
    const ui = unit('en-7');
    const sel = selectLevelItems(en, ui, createLearner(), { count: 8, rng: createRng(5), profile: normal });
    const focus = new Set(en.units[ui].newSkills);
    expect(sel.items.filter((it) => it.skills.some((s) => focus.has(s))).length).toBeGreaterThanOrEqual(3);
  });

  it('a retry keeps the objectives but changes the words and order', () => {
    const ui = unit('en-4');
    const learner = createLearner();
    const first = selectLevelItems(en, ui, learner, { count: 8, rng: createRng(11), profile: normal });
    const firstIds = first.items.map((i) => i.id);
    const retry = selectLevelItems(en, ui, learner, { count: 8, rng: createRng(12), profile: normal, previous: [firstIds] });
    const retryIds = retry.items.map((i) => i.id);
    expect(retryIds).not.toEqual(firstIds);
    const overlap = retryIds.filter((id) => firstIds.includes(id)).length;
    expect(overlap).toBeLessThanOrEqual(3);
    expect(retry.focusSkills).toEqual(first.focusSkills);
  });

  it('transfer units prefer words the child has never seen', () => {
    const ui = unit('en-6');
    const learner = createLearner();
    // The child has already read 40 CVC words.
    const seen = eligibleItems(en, ui).slice(0, 40);
    for (const it of seen) recordResult(learner, { item: it, wrongAttempts: 0, solved: true });
    let novel = 0, total = 0;
    for (let seed = 1; seed <= 10; seed++) {
      const sel = selectLevelItems(en, ui, learner, { count: 8, rng: createRng(seed), profile: normal });
      total += sel.items.length;
      novel += sel.items.filter((it) => !learner.items[it.id]).length;
    }
    expect(novel / total).toBeGreaterThan(0.6);
  });

  it('weak skills come back more often', () => {
    const ui = unit('en-4');
    const learner = createLearner();
    const items = eligibleItems(en, ui);
    // Struggles with short u, fine with everything else.
    for (const it of items.slice(0, 80)) {
      const hasU = it.skills.includes('en:G:u');
      recordResult(learner, { item: it, wrongAttempts: hasU ? 2 : 0, solved: !hasU });
    }
    let u = 0, total = 0;
    for (let seed = 1; seed <= 20; seed++) {
      const sel = selectLevelItems(en, ui, learner, { count: 8, rng: createRng(seed), profile: normal });
      total += sel.items.length;
      u += sel.items.filter((it) => it.skills.includes('en:G:u')).length;
    }
    const baseRate = items.filter((it) => it.skills.includes('en:G:u')).length / items.length;
    expect(u / total).toBeGreaterThan(baseRate);
  });

  it('Hebrew levels show Hebrew items only, from taught letters', () => {
    const he = getPack('he');
    const sel = selectLevelItems(he, 2, createLearner(), { count: 8, rng: createRng(2), profile: normal });
    for (const it of sel.items) {
      expect(it.lang).toBe('he');
      expect(['letter', 'syllable', 'word']).toContain(it.kind);
    }
  });
});
